services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  socketserver:
    build: ./socketio_server
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"