export const GAMEBOARD_WIDTH = window.innerWidth;
export const GAMEBOARD_HEIGHT = window.innerHeight;
export const ITEM_SIZE = 0.035 * GAMEBOARD_WIDTH;
export const ITEM_GAP = 0.045 * GAMEBOARD_WIDTH;
export const ROWS = 15;
export const COLS = 15;
export const ITEM_SIZE_MULTIPLIER = 0.042;
export const ITEM_GAP_MULTIPLIER = 0.05;
export const TIME_DURATION = 60;