name: Deploy backend to AWS EC2

on: 
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  Upload-Backend-Image-To-DockerHub:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: backend/
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t tanmaykule17/sumfight-backend .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Upload image to dockerhub
        run: docker push tanmaykule17/sumfight-backend:latest
    
  # Create-Backend-Task-Revision:
  #   runs-on: ubuntu-latest
  #   needs: Upload-Backend-Image-To-DockerHub
  #   steps:
  #     - name: Configure aws cli
  #       run: |
  #         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws configure set aws-secret_access_key ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
  #         aws configure set region ${{ secrets.AWS_REGION }}
  #     - name: Create new task revision
  #     - name: Update service
        
  # Pull-And-Run-Docker-Image:
  #   needs: Upload-Backend-Image-To-DockerHub
  #   runs-on: self-hosted
  #   steps:
  #     - name: Delete existing image
  #       run: docker rm tanmaykule17/sumfight-backend:latest
  #     - name: Pull docker image
  #       run: docker pull tanmaykule17/sumfight-backend:latest
  #     - name: Run docker container
  #       run: docker run -d -p 3000:3000 -e MONGODB_URI=${{ secrets.MONGODB_URI }} tanmaykule17/sumfight-backend:latest 